const SHOP_ITEMS_V43 = [
  ...["Broadsword", "Longsword", "Battleaxe", "Greatsword", "Mace", "Warhammer", "Dagger", "Quarterstaff", "Cutlass", "Rapier", "Halberd", "Spear", "Shortbow", "Crossbow", "Longbow", "Arcane Gauntlets", "Hallowed Axe", "Glowing Rings", "Hand Runes", "Returning Blade", "Shortstaff", "Dualstaff", "Scepter", "Wand", "Greatstaff"].map((name) => ({ type: "primary", tier: 1, name })),
  ...["Improved Broadsword", "Improved Longsword", "Improved Battleaxe", "Improved Greatsword", "Improved Mace", "Improved Warhammer", "Improved Dagger", "Improved Quarterstaff", "Improved Cutlass", "Improved Rapier", "Improved Halberd", "Improved Spear", "Improved Shortbow", "Improved Crossbow", "Improved Longbow", "Gilded Falchion", "Knuckle Blades", "Urok Broadsword", "Bladed Whip", "War Scythe", "Blunderbuss", "Greatbow", "Finehair Bow", "Improved Arcane Gauntlets", "Improved Hallowed Axe", "Improved Glowing Rings", "Improved Hand Runes", "Improved Returning Blade", "Improved Shortstaff", "Improved Dualstaff", "Improved Scepter", "Improved Wand", "Improved Greatstaff"].map((name) => ({ type: "primary", tier: 2, name })),
  ...["Advanced Broadsword", "Advanced Longsword", "Advanced Battleaxe", "Advanced Greatsword", "Advanced Mace", "Advanced Warhammer", "Advanced Dagger", "Advanced Quarterstaff", "Advanced Cutlass", "Advanced Rapier", "Advanced Halberd", "Advanced Spear", "Advanced Shortbow", "Advanced Crossbow", "Advanced Longbow", "Flickerfly Blade", "Bravesword", "Hammer of Wrath", "Labrys Axe", "Meridian Cutlass", "Retractable Saber", "Double Flail", "Talon Blades", "Black Powder Revolver", "Spiked Bow", "Advanced Arcane Gauntlets", "Advanced Hallowed Axe", "Advanced Glowing Rings", "Advanced Hand Runes", "Advanced Returning Blade", "Advanced Shortstaff", "Advanced Dualstaff", "Advanced Scepter", "Advanced Wand", "Advanced Greatstaff"].map((name) => ({ type: "primary", tier: 3, name })),
  ...["Legendary Broadsword", "Legendary Longsword", "Legendary Battleaxe", "Legendary Greatsword", "Legendary Mace", "Legendary Warhammer", "Legendary Dagger", "Legendary Quarterstaff", "Legendary Cutlass", "Legendary Rapier", "Legendary Halberd", "Legendary Spear", "Legendary Shortbow", "Legendary Crossbow", "Legendary Longbow", "Legendary Arcane Gauntlets", "Legendary Hallowed Axe", "Legendary Glowing Rings", "Legendary Hand Runes", "Legendary Returning Blade", "Legendary Shortstaff", "Legendary Dualstaff", "Legendary Scepter", "Legendary Wand", "Legendary Greatstaff"].map((name) => ({ type: "primary", tier: 4, name })),
  ...["Shortsword", "Round Shield", "Tower Shield", "Small Dagger", "Whip", "Grappler", "Hand Crossbow"].map((name) => ({ type: "secondary", tier: 1, name })),
  ...["Improved Shortsword", "Improved Round Shield", "Improved Tower Shield", "Improved Small Dagger", "Improved Whip", "Improved Grappler", "Improved Hand Crossbow", "Spiked Shield", "Parrying Dagger", "Returning Axe"].map((name) => ({ type: "secondary", tier: 2, name })),
  ...["Advanced Shortsword", "Advanced Round Shield", "Advanced Tower Shield", "Advanced Small Dagger", "Advanced Whip", "Advanced Grappler", "Advanced Hand Crossbow", "Buckler", "Powered Gauntlet", "Hand Sling"].map((name) => ({ type: "secondary", tier: 3, name })),
  ...["Legendary Shortsword", "Legendary Round Shield", "Legendary Tower Shield", "Legendary Small Dagger", "Legendary Whip", "Legendary Grappler", "Legendary Hand Crossbow", "Braveshield", "Knuckle Claws", "Primer Shard"].map((name) => ({ type: "secondary", tier: 4, name })),
  ...["Gambeson Armor", "Leather Armor", "Chainmail Armor", "Full Plate Armor"].map((name) => ({ type: "armor", tier: 1, name })),
  ...["Improved Gambeson Armor", "Improved Leather Armor", "Improved Chainmail Armor", "Improved Full Plate Armor", "Elundrian Chain Armor", "Harrowbone Armor", "Irontree Breastplate Armor", "Runetan Floating Armor", "Tyris Soft Armor", "Rosewild Armor"].map((name) => ({ type: "armor", tier: 2, name })),
  ...["Advanced Gambeson Armor", "Advanced Leather Armor", "Advanced Chainmail Armor", "Advanced Full Plate Armor", "Bellamie Fine Armor", "Dragonscale Armor", "Spiked Plate Armor", "Bladefare Armor", "Monett's Cloak", "Runes of Fortification"].map((name) => ({ type: "armor", tier: 3, name })),
  ...["Legendary Gambeson Armor", "Legendary Leather Armor", "Legendary Chainmail Armor", "Legendary Full Plate Armor", "Dunamis Silkchain", "Channeling Armor", "Emberwoven Armor", "Full Fortified Armor", "Veritas Opal Armor", "Savior Chainmail"].map((name) => ({ type: "armor", tier: 4, name })),
];

const SHOP_TYPE_LABEL_V43 = { primary: "\u4e3b\u6b66\u5668", secondary: "\u526f\u6b66\u5668", armor: "\u8b77\u7532" };
const SHOP_PRICE_RULE_V43 = { 1: { unit: "hand", sides: 5, label: "1d5 \u628a" }, 2: { unit: "bag", sides: 2, label: "1d2 \u888b" }, 3: { unit: "bag", sides: 6, offset: 4, label: "1d6+4 \u888b" }, 4: { unit: "box", sides: 2, label: "1d2 \u7bb1" } };

function applyShopV43(){ensureShopStylesV43();patchAssetLoggerV43();ensureShopTabV43();ensureShopPanelV43();ensureAssetLogPanelV43();updateShopVersionV43()}
function ensureShopStylesV43(){if(document.getElementById("shop-v43-style"))return;const s=document.createElement("style");s.id="shop-v43-style";s.textContent=`body[data-mode="dm"] #shopPanelV43{display:none!important}.shop-panel{display:grid;gap:8px;align-self:start}.shop-toolbar{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px}.shop-toolbar button{min-height:32px;padding:0 8px;font-size:.75rem}.shop-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;max-height:520px;overflow:auto}.shop-item{padding:7px;border:1px solid var(--line);border-radius:7px;background:rgba(18,20,23,.58);display:grid;gap:5px}.shop-item strong{font-size:.78rem}.shop-item span{color:var(--muted);font-size:.66rem}.shop-item button{min-height:30px;font-size:.72rem}.price-roll-button{margin-left:4px}.asset-log{margin-top:8px;padding-top:7px;border-top:1px solid var(--line)}.asset-log h4{font-size:.72rem;color:var(--muted);margin:0 0 5px}.asset-log ol{display:grid;gap:4px;max-height:112px;overflow:auto;margin:0;padding-left:18px}.asset-log li{font-size:.68rem;color:var(--muted);line-height:1.35}@media(min-width:720px){body[data-mode="player"] #dice.tab-panel.is-active{grid-template-columns:minmax(0,1fr) minmax(310px,.85fr)}body[data-mode="player"] #dice #shopPanelV43{grid-column:2!important;grid-row:2 / span 3}}@media(max-width:620px){.shop-grid{grid-template-columns:1fr}.shop-toolbar{grid-template-columns:repeat(2,minmax(0,1fr))}}`;document.head.appendChild(s)}
function ensureShopTabV43(){const t=document.querySelector(".tabbar");if(!t||document.getElementById("priceRollTabButton"))return;const b=document.createElement("button");b.id="priceRollTabButton";b.className="tabbar__button price-roll-button";b.type="button";b.textContent="\u64f2\u50f9\u683c";const a=document.querySelector('[data-tab="audio"]');if(a?.nextSibling)a.parentNode.insertBefore(b,a.nextSibling);else t.appendChild(b);b.addEventListener("click",()=>{rollAllShopPricesV43(true);renderShopGridV43(currentShopFilterV43())})}
function ensureShopPanelV43(){const d=document.getElementById("dice");if(!d||document.getElementById("shopPanelV43"))return;const p=document.createElement("section");p.id="shopPanelV43";p.className="tool-card shop-panel";p.innerHTML=`<div class="card-header"><div><p class="eyebrow">Shop</p><h3>\u5546\u5e97</h3></div><button class="text-button" id="rollShopPricesButton" type="button">\u64f2\u50f9\u683c</button></div><div class="shop-toolbar"><button class="text-button is-active" data-shop-filter="all" type="button">\u5168\u90e8</button><button class="text-button" data-shop-filter="primary" type="button">\u4e3b\u6b66\u5668</button><button class="text-button" data-shop-filter="secondary" type="button">\u526f\u6b66\u5668</button><button class="text-button" data-shop-filter="armor" type="button">\u8b77\u7532</button></div><div class="shop-grid" id="shopGridV43"></div>`;d.appendChild(p);p.addEventListener("click",handleShopClickV43,true);if(!state.shopPricesV43)rollAllShopPricesV43(false);renderShopGridV43()}
function ensureAssetLogPanelV43(){document.querySelectorAll("#characterList .monitor-card").forEach(card=>{const row=card.querySelector(".asset-row"),id=row?.dataset.assetCharacter;if(!row||!id)return;let log=card.querySelector(".asset-log");if(!log){log=document.createElement("div");log.className="asset-log";row.insertAdjacentElement("afterend",log)}const items=assetLogsForV43(id);log.innerHTML=`<h4>\u8cc7\u7522\u7d00\u9304</h4><ol>${items.map(x=>`<li>${escapeShopHtmlV43(x)}</li>`).join("")||`<li>\u5c1a\u7121\u7d00\u9304</li>`}</ol>`})}
function handleShopClickV43(e){const f=e.target.closest("[data-shop-filter]");if(f){document.querySelectorAll("[data-shop-filter]").forEach(b=>b.classList.toggle("is-active",b===f));renderShopGridV43(f.dataset.shopFilter);return}if(e.target.closest("#rollShopPricesButton")){rollAllShopPricesV43(true);renderShopGridV43(currentShopFilterV43());return}const buy=e.target.closest("[data-buy-shop]");if(buy)buyShopItemV43(buy.dataset.buyShop)}
function rollAllShopPricesV43(announce=true){const prices={};SHOP_ITEMS_V43.forEach((item,i)=>{const r=SHOP_PRICE_RULE_V43[item.tier],amount=Math.floor(Math.random()*r.sides)+1+(r.offset||0);prices[itemKeyV43(item,i)]={amount,unit:r.unit,label:`${amount}${unitLabelV43(r.unit)}`,rule:r.label}});state.shopPricesV43=prices;if(announce)addGlobalAssetLogV43("DM \u91cd\u64f2\u5546\u5e97\u50f9\u683c");persistShopV43();if(announce&&typeof render==="function")render()}
function renderShopGridV43(filter="all"){const grid=document.getElementById("shopGridV43");if(!grid)return;const prices=state.shopPricesV43||{};grid.innerHTML=SHOP_ITEMS_V43.map((item,i)=>({...item,key:itemKeyV43(item,i)})).filter(item=>filter==="all"||item.type===filter).map(item=>{const price=prices[item.key]||priceForItemV43(item);return`<article class="shop-item"><strong>T${item.tier} ${escapeShopHtmlV43(item.name)}</strong><span>${SHOP_TYPE_LABEL_V43[item.type]} - ${price.rule} = ${price.label}</span><button class="primary-button" data-buy-shop="${item.key}" type="button">\u8cfc\u8cb7</button></article>`}).join("")}
function buyShopItemV43(key){const entry=SHOP_ITEMS_V43.map((item,i)=>({...item,key:itemKeyV43(item,i)})).find(item=>item.key===key);if(!entry)return;const c=state.characters.find(item=>item.id===state.playerCharacterId)||state.characters[0];if(!c){alert("\u8acb\u5148\u65b0\u589e\u73a9\u5bb6\u89d2\u8272");return}const price=(state.shopPricesV43||{})[key]||priceForItemV43(entry),cost=toHandsV43(price.amount,price.unit),assets=normalizeShopAssetsV43(c);if(assets.total<cost){alert("\u8cc7\u7522\u4e0d\u8db3\uff0c\u7121\u6cd5\u8cfc\u8cb7");return}state.characters=state.characters.map(item=>item.id===c.id?{...item,assets:{total:assets.total-cost}}:item);addAssetLogV43(c.id,`${c.name} \u8cfc\u8cb7 ${entry.name}\uff0c\u82b1\u8cbb ${price.label}`);persistShopV43();if(typeof render==="function")render()}
function recordAssetChangeV43(id,unit,step){const c=state.characters.find(item=>item.id===id);if(!c||!step)return;const sign=step>0?"+":"";addAssetLogV43(id,`${c.name} \u8cc7\u7522 ${sign}${step}${unitLabelV43(unit)}`);persistShopV43()}
function patchAssetLoggerV43(){if(window.assetLoggerPatchedV43||typeof window.updateCharacterAssetV41!=="function")return;const original=window.updateCharacterAssetV41;window.updateCharacterAssetV41=function(id,unit,step){original(id,unit,step);recordAssetChangeV43(id,unit,Number(step));ensureAssetLogPanelV43()};try{updateCharacterAssetV41=window.updateCharacterAssetV41}catch(error){}window.assetLoggerPatchedV43=true}
function priceForItemV43(item){const r=SHOP_PRICE_RULE_V43[item.tier];return{amount:1,unit:r.unit,label:`1${unitLabelV43(r.unit)}`,rule:r.label}}
function itemKeyV43(item,i){return`${item.type}-${item.tier}-${i}`}
function toHandsV43(amount,unit){return unit==="box"?amount*100:unit==="bag"?amount*10:amount}
function unitLabelV43(unit){return unit==="box"?"\u7bb1":unit==="bag"?"\u888b":"\u628a"}
function normalizeShopAssetsV43(c){if(typeof normalizeAssetsV41==="function")return normalizeAssetsV41(c);return{total:Number(c.assets?.total||0)}}
function currentShopFilterV43(){return document.querySelector("[data-shop-filter].is-active")?.dataset.shopFilter||"all"}
function addAssetLogV43(id,text){state.assetLogsV43=state.assetLogsV43||{};state.assetLogsV43[id]=[`${new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})} ${text}`,...(state.assetLogsV43[id]||[])].slice(0,20)}
function addGlobalAssetLogV43(text){state.assetLogsV43=state.assetLogsV43||{};state.assetLogsV43.global=[`${new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})} ${text}`,...(state.assetLogsV43.global||[])].slice(0,20)}
function assetLogsForV43(id){return[...(state.assetLogsV43?.[id]||[]),...(state.assetLogsV43?.global||[]).slice(0,3)].slice(0,8)}
function persistShopV43(){if(typeof writeAssetShadowV41==="function")writeAssetShadowV41();if(typeof save==="function")save();else if(typeof saveState==="function")saveState();if(typeof saveCloudState==="function"){window.clearTimeout(window.shopCloudSaveV43);window.shopCloudSaveV43=window.setTimeout(()=>saveCloudState(),30)}}
function updateShopVersionV43(){const v=document.querySelector(".session-strip .status-pill");if(v)v.textContent="v0.1.14 \u5546\u5e97\u7248"}
function escapeShopHtmlV43(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c])}
if(typeof render==="function"&&!window.shopRenderPatchedV43){const originalRenderV43=render;render=function(){originalRenderV43();applyShopV43()};window.shopRenderPatchedV43=true}
window.recordAssetChangeV43=recordAssetChangeV43;window.addEventListener("load",applyShopV43);applyShopV43();
