import { loadState, saveState } from "./modules/storage.js";
import { addAssetEntry, addCharacterEffect, addCharacter, adjustCharacterAttribute, adjustCharacterGold, adjustCharacterMoney, adjustCharacterStat, deleteAssetEntry, deleteCharacter, deleteCharacterEffect, expandCharacter, selectCharacter, toggleCharacterEffect, updateAssetEntry, updateCharacterAttribute, updateCharacterField, updateCharacterGold, updateCharacterMoney, updateCharacterStat } from "./modules/characters.js";
import { addRoll, appendFormulaToken, applyDualityEffects, clearRolls, rollDuality, rollFormula } from "./modules/dice.js";
import { addMonster, adjustMonsterValue, advanceMonsterRound, deleteMonster, expandMonster, resetMonsterRound, rollMonsterAction, updateMonster } from "./modules/monsters.js";
import { updatePublicInfoField } from "./modules/public-info.js";
import { addShopItem, deleteShopItem, purchaseShopItem, updateShopItem } from "./modules/shop.js";
import { createDefaultState } from "./modules/state.js";
import { getActivePageId, getActivePages, setActivePage, setMode } from "./modules/router.js";
import { renderDmPage } from "./modules/dm-view.js";
import { renderPlayerPage } from "./modules/player-view.js";

const app = document.querySelector("#app");
const DEFAULT_BUILD_INFO = { version: "v2", label: "version-check", commit: "unknown", updatedAt: "", note: "" };
let state = saveState(loadState()); let isDmMenuOpen = false; let buildInfo = { ...DEFAULT_BUILD_INFO };
function updateState(nextState) { state = saveState(nextState); render(); }
function saveStateOnly(nextState) { state = saveState(nextState); }
function appendRollToken(button) { const input = button.closest(".dice-panel")?.querySelector("[data-roll-formula]"); if (!input) return; input.value = appendFormulaToken(input.value, button.dataset.rollToken); input.focus(); }
function renderModeButton(mode, label) { const active=state.ui.mode===mode; return `<button class="mode-button ${active?"is-active":""}" type="button" data-mode="${mode}" aria-pressed="${active}">${label}</button>`; }
function renderPageButton(page, className) { const active=page.id===getActivePageId(state); return `<button class="${className} ${active?"is-active":""}" type="button" data-page="${page.id}" aria-pressed="${active}">${page.label}</button>`; }
function shortCommit(commit){return commit?String(commit).slice(0,7):"unknown";}
function renderBuildLabel(){return `${buildInfo.version} · ${buildInfo.label} · ${shortCommit(buildInfo.commit)}`;}
async function loadBuildInfo(){try{const r=await fetch(`./version.json?ts=${Date.now()}`,{cache:"no-store"});if(r.ok)buildInfo={...DEFAULT_BUILD_INFO,...await r.json()};}catch{} console.info(`TRPG Assistant v2 build: ${buildInfo.label} / ${shortCommit(buildInfo.commit)}`);render();}
function renderPanel(){const pages=getActivePages(state.ui.mode);const page=pages.find(x=>x.id===getActivePageId(state))||pages[0];return state.ui.mode==="player"?renderPlayerPage(page.id,state):renderDmPage(page.id,state);}
function renderDmMobileNav(pages){const active=pages.find(p=>p.id===getActivePageId(state))||pages[0];return `<div class="dm-mobile-nav"><button class="dm-menu-button" type="button" data-dm-menu-toggle aria-expanded="${isDmMenuOpen}"><span>☰</span><span>DM 選單</span></button><strong>${active.label}</strong></div><nav class="dm-mobile-menu ${isDmMenuOpen?"is-open":""}">${pages.map(p=>renderPageButton(p,"dm-mobile-menu-button")).join("")}</nav>`;}
function render(){const pages=getActivePages(state.ui.mode);const player=state.ui.mode==="player";app.innerHTML=`<header class="app-header"><div class="brand-block"><p class="eyebrow">TRPG Assistant</p><h1 class="app-title">v2 基礎架構</h1><p class="app-subtitle">HTML / CSS / 原生 JS / ES Modules / localStorage</p></div><nav class="mode-switch">${renderModeButton("player","玩家")}${renderModeButton("dm","DM")}</nav></header><main class="layout ${player?"is-player":"is-dm"}">${player?`<nav class="tab-list player-bottom-tabs">${pages.map(p=>renderPageButton(p,"tab-button")).join("")}</nav>`:renderDmMobileNav(pages)}<nav class="sidebar-list">${pages.map(p=>renderPageButton(p,"sidebar-button")).join("")}</nav>${renderPanel()}</main><p class="footer-note" data-version-label>${renderBuildLabel()}</p>`;}

app.addEventListener("click",event=>{const mode=event.target.closest("[data-mode]");const page=event.target.closest("[data-page]");const menu=event.target.closest("[data-dm-menu-toggle]");const b=event.target.closest("[data-action]");if(menu){isDmMenuOpen=!isDmMenuOpen;render();return;}if(mode){isDmMenuOpen=false;updateState(setMode(state,mode.dataset.mode));return;}if(page){isDmMenuOpen=false;updateState(setActivePage(state,page.dataset.page));}if(!b)return;const a=b.dataset.action;
if(a==="toggle-team-status"){updateState({...state,ui:{...state.ui,isTeamStatusOpen:!state.ui.isTeamStatusOpen}});return;}
if(a==="delete-character"){updateState(deleteCharacter(state,b.dataset.characterId));return;}if(a==="expand-character"){updateState(expandCharacter(state,b.dataset.characterId));return;}
if(a==="adjust-character-stat"){updateState(adjustCharacterStat(state,b.dataset.characterId,b.dataset.statField,Number(b.dataset.delta)));return;}if(a==="adjust-character-attribute"){updateState(adjustCharacterAttribute(state,b.dataset.characterId,b.dataset.attributeField,Number(b.dataset.delta)));return;}if(a==="adjust-character-money"){updateState(adjustCharacterMoney(state,b.dataset.characterId,Number(b.dataset.delta)));return;}if(a==="adjust-character-gold"){updateState(adjustCharacterGold(state,b.dataset.characterId,b.dataset.goldField,Number(b.dataset.delta)));return;}
if(a==="delete-character-effect"){updateState(deleteCharacterEffect(state,b.dataset.characterId,b.dataset.effectType,Number(b.dataset.effectIndex)));return;}if(a==="toggle-character-effect"){updateState(toggleCharacterEffect(state,b.dataset.characterId,b.dataset.effectType,b.dataset.effectLabel));return;}if(a==="delete-asset-entry"){updateState(deleteAssetEntry(state,b.dataset.characterId,b.dataset.listKey,Number(b.dataset.entryIndex)));return;}
if(a==="clear-rolls"){updateState(clearRolls(state));return;}if(a==="append-roll-token"){appendRollToken(b);return;}if(a==="roll-duality"){const target=b.closest(".dice-panel")?.querySelector("[data-duality-target]")?.value;const applied=applyDualityEffects(state,rollDuality({target}));updateState(addRoll(applied.state,applied.roll,b.dataset.rollActor||"玩家"));return;}
if(a==="delete-shop-item"){if(confirm("確定要刪除這個商品嗎？"))updateState(deleteShopItem(state,b.dataset.shopItemId));return;}if(a==="purchase-shop-item"){updateState(purchaseShopItem(state,b.dataset.shopItemId));return;}
if(a==="delete-monster"){if(confirm("確定要刪除這隻怪物嗎？"))updateState(deleteMonster(state,b.dataset.monsterId));return;}if(a==="adjust-monster"){updateState(adjustMonsterValue(state,b.dataset.monsterId,b.dataset.monsterField,Number(b.dataset.delta)));return;}if(a==="expand-monster"){updateState(expandMonster(state,b.dataset.monsterId));return;}if(a==="roll-monster-attack"){updateState(rollMonsterAction(state,b.dataset.monsterId,"attack"));return;}if(a==="roll-monster-damage"){updateState(rollMonsterAction(state,b.dataset.monsterId,"damage"));return;}if(a==="next-monster-round"){updateState(advanceMonsterRound(state));return;}if(a==="reset-monster-round"){if(confirm("確定要重設怪物回合？")&&confirm("再次確認：回合將回到 0。"))updateState(resetMonsterRound(state));return;}
if(a==="reset-v2-state"&&confirm("確定要重設 v2 測試資料嗎？")&&confirm("再次確認：這會清空目前 v2 localStorage。"))updateState(createDefaultState());});

app.addEventListener("change",event=>{const sel=event.target.closest("[data-character-select]");if(sel)updateState(selectCharacter(state,sel.value));const shop=event.target.closest("[data-shop-item-field]");if(shop)updateState(updateShopItem(state,shop.dataset.shopItemId,shop.dataset.shopItemField,shop.value));const id=event.target.dataset.characterId;if(!id)return;if(event.target.dataset.characterField)updateState(updateCharacterField(state,id,event.target.dataset.characterField,event.target.value));else if(event.target.dataset.statField)updateState(updateCharacterStat(state,id,event.target.dataset.statField,event.target.value));else if(event.target.dataset.attributeField)updateState(updateCharacterAttribute(state,id,event.target.dataset.attributeField,event.target.value));else if(event.target.dataset.goldField)updateState(updateCharacterGold(state,id,event.target.dataset.goldField,event.target.value));else if(event.target.matches("[data-money-field]"))updateState(updateCharacterMoney(state,id,event.target.value));});
app.addEventListener("input",event=>{const id=event.target.dataset.characterId;if(id){if(event.target.dataset.characterField)return saveStateOnly(updateCharacterField(state,id,event.target.dataset.characterField,event.target.value));if(event.target.dataset.statField)return saveStateOnly(updateCharacterStat(state,id,event.target.dataset.statField,event.target.value));if(event.target.dataset.attributeField)return saveStateOnly(updateCharacterAttribute(state,id,event.target.dataset.attributeField,event.target.value));if(event.target.dataset.goldField)return saveStateOnly(updateCharacterGold(state,id,event.target.dataset.goldField,event.target.value));if(event.target.matches("[data-money-field]"))return saveStateOnly(updateCharacterMoney(state,id,event.target.value));}const asset=event.target.closest("[data-asset-entry-field]");if(asset)return saveStateOnly(updateAssetEntry(state,asset.dataset.characterId,asset.dataset.listKey,Number(asset.dataset.entryIndex),asset.value));const pub=event.target.dataset.publicInfoField;if(pub)return saveStateOnly(updatePublicInfoField(state,pub,event.target.value));const shop=event.target.closest("[data-shop-item-field]");if(shop)return saveStateOnly(updateShopItem(state,shop.dataset.shopItemId,shop.dataset.shopItemField,shop.value));const monster=event.target.closest("[data-monster-field]");if(monster)saveStateOnly(updateMonster(state,monster.dataset.monsterId,monster.dataset.monsterField,monster.value));});
app.addEventListener("submit",event=>{const form=event.target;if(form.matches("[data-add-character-form]")){event.preventDefault();updateState(addCharacter(state,form.querySelector("[data-new-character-name]").value.trim(),form.querySelector("[data-new-character-color]")?.value));return;}if(form.matches("[data-add-character-effect-form]")){event.preventDefault();updateState(addCharacterEffect(state,form.dataset.characterId,form.dataset.effectType,form.querySelector("[data-character-effect-input]").value));return;}if(form.matches("[data-add-asset-form]")){event.preventDefault();updateState(addAssetEntry(state,form.dataset.characterId,form.dataset.listKey,form.querySelector("[data-asset-entry-input]").value));return;}if(form.matches("[data-add-shop-item-form]")){event.preventDefault();updateState(addShopItem(state,{name:form.querySelector("[data-new-shop-name]").value.trim(),type:form.querySelector("[data-new-shop-type]").value,price:form.querySelector("[data-new-shop-price]").value,stock:form.querySelector("[data-new-shop-stock]").value,description:form.querySelector("[data-new-shop-description]").value}));return;}if(form.matches("[data-add-monster-form]")){event.preventDefault();const values=Object.fromEntries([...form.querySelectorAll("[data-new-monster-field]")].map(i=>[i.dataset.newMonsterField,i.value]));updateState(addMonster(state,values));return;}if(form.matches("[data-roll-form]")){event.preventDefault();const input=form.querySelector("[data-roll-formula]");const result=rollFormula(input.value);const message=form.parentElement.querySelector("[data-roll-message]");if(!result.ok){if(message)message.textContent=result.error;return;}if(message)message.textContent="";updateState(addRoll(state,result,form.dataset.rollActor||"玩家"));}});
app.addEventListener("wheel",event=>{const stepper=event.target.closest("[data-number-stepper]");if(!stepper)return;event.preventDefault();const d=event.deltaY<0?1:-1;const {characterId,stepperType,stepperField}=stepper.dataset;if(stepperType==="stat")updateState(adjustCharacterStat(state,characterId,stepperField,d));else if(stepperType==="attribute")updateState(adjustCharacterAttribute(state,characterId,stepperField,d));else if(stepperType==="money")updateState(adjustCharacterMoney(state,characterId,d));else if(stepperType==="gold")updateState(adjustCharacterGold(state,characterId,stepperField,d));},{passive:false});
render();loadBuildInfo();
